import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :ga_personal_web, GaPersonalWeb.Endpoint,
  url: [host: "api.guialmeidapersonal.esp.br", port: 443, scheme: "https"],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Don't force SSL at app level - the GCP Load Balancer handles SSL termination
# and forwards requests over HTTP internally. The health check also needs HTTP.
# config :ga_personal_web, GaPersonalWeb.Endpoint,
#   force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
