defmodule GaPersonalWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :ga_personal_web

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_ga_personal_web_key",
    signing_salt: "/W1EO8Vr",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :ga_personal_web,
    gzip: not code_reloading?,
    only: GaPersonalWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :ga_personal_web
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS - must be before Router to handle OPTIONS preflight requests
  plug CORSPlug,
    origin: [
      # Development
      "http://localhost:3001",
      "http://localhost:3002",
      "http://localhost:3003",
      # Production - esp.br domain
      "https://guialmeidapersonal.esp.br",
      "https://www.guialmeidapersonal.esp.br",
      "https://admin.guialmeidapersonal.esp.br",
      "https://app.guialmeidapersonal.esp.br",
      # Production - com.br domain (future)
      "https://guialmeidapersonal.com.br",
      "https://www.guialmeidapersonal.com.br",
      "https://admin.guialmeidapersonal.com.br",
      "https://app.guialmeidapersonal.com.br"
    ],
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    headers: ["Authorization", "Content-Type", "Accept", "Origin", "User-Agent", "X-Requested-With"]

  plug GaPersonalWeb.Router
end
